
try:
    from pymol import cmd
except ImportError:
    print("PyMOL Python lib is missing")
    # sys.exit(0)

def spl_extract():
 for name in cmd.get_names("all"):
    #if name in ['5zwo', '5gm6', '5lj3', '5mps', '6exn', '5ylz', '5y88', '3jb9', '6icz', '6ff7', '5yzg', '5xjc', '5gan', '6qw6', '3jcr', '6qx9', '6ah0']: # this should be auto
    print(" \ Extracting mode for %s" % name)

    
    for n in cmd.get_names("all"):
        if '5zwo' in n:
            object_name = n
            print(object_name)
            
    if '5zwo' in name.lower():
        cmd.extract("PRP8_B5zwo", "chain A and " + object_name)
        cmd.extract("BRR2_B5zwo", "chain D and " + object_name)
        cmd.extract("LEA1_B5zwo", "chain o and " + object_name)
        cmd.extract("Msl1_B5zwo", "chain p and " + object_name)
        cmd.extract("SNU114_B5zwo", "chain C and " + object_name)
        cmd.extract("U2_B5zwo", "chain H and " + object_name)
        cmd.extract("U5_B5zwo", "chain B and " + object_name)
        cmd.extract("U6_B5zwo", "chain F and " + object_name)
        cmd.extract("U4_B5zwo", "chain I and " + object_name)
        cmd.extract("Intron_B5zwo", "chain G and " + object_name)
        cmd.extract("PRP4_B5zwo", "chain K and " + object_name)
        cmd.extract("PRP31_B5zwo", "chain L and " + object_name)
        cmd.extract("PRP6_B5zwo", "chain N and " + object_name)
        cmd.extract("PRP3_B5zwo", "chain J and " + object_name)
        cmd.extract("DIB1_B5zwo", "chain E and " + object_name)
        cmd.extract("SNU13_B5zwo", "chain M and " + object_name)
        cmd.extract("LSM8_B5zwo", "chain z and " + object_name)
        cmd.extract("LSM2_B5zwo", "chain q and " + object_name)
        cmd.extract("LSM3_B5zwo", "chain r and " + object_name)
        cmd.extract("LSM6_B5zwo", "chain x and " + object_name)
        cmd.extract("LSM5_B5zwo", "chain t and " + object_name)
        cmd.extract("LSM7_B5zwo", "chain y and " + object_name)
        cmd.extract("LSM4_B5zwo", "chain s and " + object_name)
        cmd.extract("SNU66_B5zwo", "chain O and " + object_name)
        cmd.extract("BUD13_B5zwo", "chain Y and " + object_name)
        cmd.extract("Cus1_B5zwo", "chain 2 and " + object_name)
        cmd.extract("HSH155_B5zwo", "chain 1 and " + object_name)
        cmd.extract("HSH49_B5zwo", "chain 4 and " + object_name)
        cmd.extract("PML1_B5zwo", "chain Z and " + object_name)
        cmd.extract("PRP11_B5zwo", "chain v and " + object_name)
        cmd.extract("RDS3_B5zwo", "chain 5 and " + object_name)
        cmd.extract("RSE1_B5zwo", "chain 3 and " + object_name)
        cmd.extract("SNU17_B5zwo", "chain X and " + object_name)
        cmd.extract("Ysf3_B5zwo", "chain 6 and " + object_name)
        cmd.extract("SMB1_1_B5zwo", "chain a and " + object_name)
        cmd.extract("SMB1_2_B5zwo", "chain P and " + object_name)
        cmd.extract("SMB1_3_B5zwo", "chain h and " + object_name)
        cmd.extract("SME1_1_B5zwo", "chain e and " + object_name)
        cmd.extract("SME1_2_B5zwo", "chain T and " + object_name)
        cmd.extract("SME1_3_B5zwo", "chain i and " + object_name)
        cmd.extract("SMX3_1_B5zwo", "chain f and " + object_name)
        cmd.extract("SMX3_2_B5zwo", "chain U and " + object_name)
        cmd.extract("SMX3_3_B5zwo", "chain j and " + object_name)
        cmd.extract("SMX2_1_B5zwo", "chain g and " + object_name)
        cmd.extract("SMX2_2_B5zwo", "chain V and " + object_name)
        cmd.extract("SMX2_3_B5zwo", "chain k and " + object_name)
        cmd.extract("SMD3_1_B5zwo", "chain d and " + object_name)
        cmd.extract("SMD3_2_B5zwo", "chain S and " + object_name)
        cmd.extract("SMD3_3_B5zwo", "chain l and " + object_name)
        cmd.extract("SMD1_1_B5zwo", "chain b and " + object_name)
        cmd.extract("SMD1_2_B5zwo", "chain Q and " + object_name)
        cmd.extract("SMD1_3_B5zwo", "chain m and " + object_name)
        cmd.extract("SMD2_1_B5zwo", "chain c and " + object_name)
        cmd.extract("SMD2_2_B5zwo", "chain R and " + object_name)
        cmd.extract("SMD2_3_B5zwo", "chain n and " + object_name)
        cmd.extract("PRP9_B5zwo", "chain u and " + object_name)
        cmd.extract("PRP21_B5zwo", "chain w and " + object_name)
        cmd.extract("SNU23_B5zwo", "chain W and " + object_name)
        cmd.extract("PRP38_B5zwo", "chain 0 and " + object_name)
        cmd.extract("SPP381_B5zwo", "chain 9 and " + object_name)
        cmd.set_name(object_name, "unknown_other_B5zwo")
        cmd.group("B5zwo", "*_B5zwo")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5gm6' in n:
            object_name = n
            print(object_name)
            
    if '5gm6' in name.lower():
        cmd.extract("PRP8_Ba5gm6", "chain A and " + object_name)
        cmd.extract("BRR2_Ba5gm6", "chain B and " + object_name)
        cmd.extract("BUD31_Ba5gm6", "chain T and " + object_name)
        cmd.extract("CEF1_Ba5gm6", "chain c and " + object_name)
        cmd.extract("CWC15_Ba5gm6", "chain S and " + object_name)
        cmd.extract("CWC2_hRBM22_Ba5gm6", "chain R and " + object_name)
        cmd.extract("CWC21_Ba5gm6", "chain X and " + object_name)
        cmd.extract("CWC22_Ba5gm6", "chain Z and " + object_name)
        cmd.extract("PRP45_Ba5gm6", "chain P and " + object_name)
        cmd.extract("CDC40_Ba5gm6", "chain n and " + object_name)
        cmd.extract("PRP19_Ba5gm6", "chain f and " + object_name)
        cmd.extract("PRP46_Ba5gm6", "chain O and " + object_name)
        cmd.extract("SLT11/ECM2_Ba5gm6", "chain Q and " + object_name)
        cmd.extract("SNT309_Ba5gm6", "chain t and " + object_name)
        cmd.extract("SNU114_Ba5gm6", "chain C and " + object_name)
        cmd.extract("SYF2_Ba5gm6", "chain f and " + object_name)
        cmd.extract("SYF1_Ba5gm6", "chain v and " + object_name)
        cmd.extract("U2_Ba5gm6", "chain 2 and " + object_name)
        cmd.extract("U5_Ba5gm6", "chain 5 and " + object_name)
        cmd.extract("U6_Ba5gm6", "chain 6 and " + object_name)
        cmd.extract("Intron_Ba5gm6", "chain M and " + object_name)
        cmd.extract("Exon_Ba5gm6", "chain N and " + object_name)
        cmd.extract("BUD13_Ba5gm6", "chain W and " + object_name)
        cmd.extract("CLF2_Ba5gm6", "chain d and " + object_name)
        cmd.extract("Cus1_Ba5gm6", "chain H and " + object_name)
        cmd.extract("CWC24_Ba5gm6", "chain a and " + object_name)
        cmd.extract("CWC27_Ba5gm6", "chain b and " + object_name)
        cmd.extract("HSH155_Ba5gm6", "chain G and " + object_name)
        cmd.extract("HSH49_Ba5gm6", "chain e and " + object_name)
        cmd.extract("PML1_Ba5gm6", "chain U and " + object_name)
        cmd.extract("PRP11_Ba5gm6", "chain I and " + object_name)
        cmd.extract("PRP2_Ba5gm6", "chain Y and " + object_name)
        cmd.extract("RDS3_Ba5gm6", "chain J and " + object_name)
        cmd.extract("RSE1_Ba5gm6", "chain F and " + object_name)
        cmd.extract("SNU17_Ba5gm6", "chain V and " + object_name)
        cmd.extract("Ysf3_Ba5gm6", "chain K and " + object_name)
        cmd.set_name(object_name, "unknown_other_Ba5gm6")
        cmd.group("Ba5gm6", "*_Ba5gm6")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5lj3' in n:
            object_name = n
            print(object_name)
            
    if '5lj3' in name.lower():
        cmd.extract("PRP8_C5lj3", "chain A and " + object_name)
        cmd.extract("BUD31_C5lj3", "chain L and " + object_name)
        cmd.extract("CEF1_C5lj3", "chain O and " + object_name)
        cmd.extract("CLF1_C5lj3", "chain S and " + object_name)
        cmd.extract("CWC15_C5lj3", "chain P and " + object_name)
        cmd.extract("CWC16/YJU2_C5lj3", "chain D and " + object_name)
        cmd.extract("CWC2_hRBM22_C5lj3", "chain M and " + object_name)
        cmd.extract("CWC21_C5lj3", "chain R and " + object_name)
        cmd.extract("CWC22_C5lj3", "chain H and " + object_name)
        cmd.extract("CWC25_C5lj3", "chain F and " + object_name)
        cmd.extract("ISY1_C5lj3", "chain G and " + object_name)
        cmd.extract("LEA1_C5lj3", "chain W and " + object_name)
        cmd.extract("Msl1_C5lj3", "chain Y and " + object_name)
        cmd.extract("PRP45_C5lj3", "chain K and " + object_name)
        cmd.extract("PRP46_C5lj3", "chain J and " + object_name)
        cmd.extract("SLT11/ECM2_C5lj3", "chain N and " + object_name)
        cmd.extract("SNU114_C5lj3", "chain C and " + object_name)
        cmd.extract("SYF1_C5lj3", "chain T and " + object_name)
        cmd.extract("U2_C5lj3", "chain Z and " + object_name)
        cmd.extract("U5_C5lj3", "chain U and " + object_name)
        cmd.extract("U6_C5lj3", "chain V and " + object_name)
        cmd.extract("Intron_C5lj3", "chain I and " + object_name)
        cmd.extract("Exon_C5lj3", "chain E and " + object_name)
        cmd.extract("SMB1_1_C5lj3", "chain b and " + object_name)
        cmd.extract("SMB1_2_C5lj3", "chain k and " + object_name)
        cmd.extract("SME1_1_C5lj3", "chain e and " + object_name)
        cmd.extract("SME1_2_C5lj3", "chain p and " + object_name)
        cmd.extract("SMX3_1_C5lj3", "chain f and " + object_name)
        cmd.extract("SMX3_2_C5lj3", "chain q and " + object_name)
        cmd.extract("SMX2_1_C5lj3", "chain g and " + object_name)
        cmd.extract("SMX2_2_C5lj3", "chain r and " + object_name)
        cmd.extract("SMD3_1_C5lj3", "chain d and " + object_name)
        cmd.extract("SMD3_2_C5lj3", "chain n and " + object_name)
        cmd.extract("SMD1_1_C5lj3", "chain h and " + object_name)
        cmd.extract("SMD1_2_C5lj3", "chain l and " + object_name)
        cmd.extract("SMD2_1_C5lj3", "chain j and " + object_name)
        cmd.extract("SMD2_2_C5lj3", "chain m and " + object_name)
        cmd.set_name(object_name, "unknown_other_C5lj3")
        cmd.group("C5lj3", "*_C5lj3")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5mps' in n:
            object_name = n
            print(object_name)
            
    if '5mps' in name.lower():
        cmd.extract("PRP8_Cs5mps", "chain A and " + object_name)
        cmd.extract("BUD31_Cs5mps", "chain L and " + object_name)
        cmd.extract("CEF1_Cs5mps", "chain O and " + object_name)
        cmd.extract("CLF1_Cs5mps", "chain S and " + object_name)
        cmd.extract("CWC15_Cs5mps", "chain P and " + object_name)
        cmd.extract("CWC2_hRBM22_Cs5mps", "chain M and " + object_name)
        cmd.extract("CWC21_Cs5mps", "chain R and " + object_name)
        cmd.extract("CWC22_Cs5mps", "chain H and " + object_name)
        cmd.extract("PRP45_Cs5mps", "chain K and " + object_name)
        cmd.extract("CDC40_Cs5mps", "chain o and " + object_name)
        cmd.extract("PRP46_Cs5mps", "chain J and " + object_name)
        cmd.extract("SLT11/ECM2_Cs5mps", "chain N and " + object_name)
        cmd.extract("SNU114_Cs5mps", "chain C and " + object_name)
        cmd.extract("SYF2_Cs5mps", "chain y and " + object_name)
        cmd.extract("SYF1_Cs5mps", "chain T and " + object_name)
        cmd.extract("U2_Cs5mps", "chain 2 and " + object_name)
        cmd.extract("U5_Cs5mps", "chain 5 and " + object_name)
        cmd.extract("U6_Cs5mps", "chain 6 and " + object_name)
        cmd.extract("5EXON_Cs5mps", "chain E and " + object_name)
        cmd.extract("Intron_Cs5mps", "chain I and " + object_name)
        cmd.extract("Exon_Cs5mps", "chain E and " + object_name)
        cmd.extract("SMB1_Cs5mps", "chain b and " + object_name)
        cmd.extract("SME1_Cs5mps", "chain e and " + object_name)
        cmd.extract("SMX3_Cs5mps", "chain f and " + object_name)
        cmd.extract("SMX2_Cs5mps", "chain g and " + object_name)
        cmd.extract("SMD3_Cs5mps", "chain d and " + object_name)
        cmd.extract("SMD1_Cs5mps", "chain h and " + object_name)
        cmd.extract("SMD2_Cs5mps", "chain j and " + object_name)
        cmd.extract("PRP18_Cs5mps", "chain a and " + object_name)
        cmd.extract("SLU7_Cs5mps", "chain c and " + object_name)
        cmd.set_name(object_name, "unknown_other_Cs5mps")
        cmd.group("Cs5mps", "*_Cs5mps")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6exn' in n:
            object_name = n
            print(object_name)
            
    if '6exn' in name.lower():
        cmd.extract("PRP8_P6exn", "chain A and " + object_name)
        cmd.extract("BUD31_P6exn", "chain L and " + object_name)
        cmd.extract("CEF1_P6exn", "chain O and " + object_name)
        cmd.extract("CLF1_P6exn", "chain S and " + object_name)
        cmd.extract("CWC15_P6exn", "chain P and " + object_name)
        cmd.extract("CWC16/YJU2_P6exn", "chain D and " + object_name)
        cmd.extract("CWC2_hRBM22_P6exn", "chain M and " + object_name)
        cmd.extract("CWC21_P6exn", "chain R and " + object_name)
        cmd.extract("CWC22_P6exn", "chain H and " + object_name)
        cmd.extract("LEA1_P6exn", "chain W and " + object_name)
        cmd.extract("Msl1_P6exn", "chain Y and " + object_name)
        cmd.extract("PRP45_P6exn", "chain K and " + object_name)
        cmd.extract("CDC40_P6exn", "chain o and " + object_name)
        cmd.extract("PRP19_1_P6exn", "chain t and " + object_name)
        cmd.extract("PRP19_2_P6exn", "chain u and " + object_name)
        cmd.extract("PRP19_3_P6exn", "chain v and " + object_name)
        cmd.extract("PRP19_4_P6exn", "chain w and " + object_name)
        cmd.extract("PRP46_P6exn", "chain J and " + object_name)
        cmd.extract("SLT11/ECM2_P6exn", "chain N and " + object_name)
        cmd.extract("SNU114_P6exn", "chain C and " + object_name)
        cmd.extract("SYF1_P6exn", "chain T and " + object_name)
        cmd.extract("U2_P6exn", "chain 2 and " + object_name)
        cmd.extract("U5_P6exn", "chain 5 and " + object_name)
        cmd.extract("U6_P6exn", "chain 6 and " + object_name)
        cmd.extract("Intron_P6exn", "chain I and " + object_name)
        cmd.extract("Exon_P6exn", "chain E and " + object_name)
        cmd.extract("SMB1_1_P6exn", "chain b and " + object_name)
        cmd.extract("SMB1_2_P6exn", "chain k and " + object_name)
        cmd.extract("SME1_1_P6exn", "chain e and " + object_name)
        cmd.extract("SME1_2_P6exn", "chain p and " + object_name)
        cmd.extract("SMX3_1_P6exn", "chain f and " + object_name)
        cmd.extract("SMX3_2_P6exn", "chain q and " + object_name)
        cmd.extract("SMX2_1_P6exn", "chain g and " + object_name)
        cmd.extract("SMX2_2_P6exn", "chain r and " + object_name)
        cmd.extract("SMD3_1_P6exn", "chain d and " + object_name)
        cmd.extract("SMD3_2_P6exn", "chain n and " + object_name)
        cmd.extract("SMD1_1_P6exn", "chain h and " + object_name)
        cmd.extract("SMD1_2_P6exn", "chain l and " + object_name)
        cmd.extract("SMD2_1_P6exn", "chain j and " + object_name)
        cmd.extract("SMD2_2_P6exn", "chain m and " + object_name)
        cmd.extract("PRP22_P6exn", "chain V and " + object_name)
        cmd.extract("PRP18_P6exn", "chain a and " + object_name)
        cmd.extract("SLU7_P6exn", "chain c and " + object_name)
        cmd.extract("unassigned_P6exn", "chain X and " + object_name)
        cmd.set_name(object_name, "unknown_other_P6exn")
        cmd.group("P6exn", "*_P6exn")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5ylz' in n:
            object_name = n
            print(object_name)
            
    if '5ylz' in name.lower():
        cmd.extract("PRP8_P5ylz", "chain A and " + object_name)
        cmd.extract("BUD31_P5ylz", "chain L and " + object_name)
        cmd.extract("CEF1_P5ylz", "chain J and " + object_name)
        cmd.extract("CLF1_P5ylz", "chain I and " + object_name)
        cmd.extract("CWC15_P5ylz", "chain P and " + object_name)
        cmd.extract("CWC2_hRBM22_P5ylz", "chain N and " + object_name)
        cmd.extract("CWC21_P5ylz", "chain R and " + object_name)
        cmd.extract("CWC22_P5ylz", "chain S and " + object_name)
        cmd.extract("LEA1_P5ylz", "chain o and " + object_name)
        cmd.extract("Msl1_P5ylz", "chain p and " + object_name)
        cmd.extract("PRP45_P5ylz", "chain Q and " + object_name)
        cmd.extract("CDC40_P5ylz", "chain T and " + object_name)
        cmd.extract("PRP19_1_P5ylz", "chain q and " + object_name)
        cmd.extract("PRP19_2_P5ylz", "chain r and " + object_name)
        cmd.extract("PRP19_3_P5ylz", "chain s and " + object_name)
        cmd.extract("PRP19_4_P5ylz", "chain t and " + object_name)
        cmd.extract("PRP46_P5ylz", "chain O and " + object_name)
        cmd.extract("SLT11/ECM2_P5ylz", "chain M and " + object_name)
        cmd.extract("SNT309_P5ylz", "chain G and " + object_name)
        cmd.extract("SNU114_P5ylz", "chain C and " + object_name)
        cmd.extract("SYF2_P5ylz", "chain K and " + object_name)
        cmd.extract("SYF1_P5ylz", "chain H and " + object_name)
        cmd.extract("U2_P5ylz", "chain F and " + object_name)
        cmd.extract("U5_P5ylz", "chain B and " + object_name)
        cmd.extract("U6_P5ylz", "chain D and " + object_name)
        cmd.extract("Intron_P5ylz", "chain E and " + object_name)
        cmd.extract("SMB1_1_P5ylz", "chain a and " + object_name)
        cmd.extract("SMB1_2_P5ylz", "chain h and " + object_name)
        cmd.extract("SME1_1_P5ylz", "chain b and " + object_name)
        cmd.extract("SME1_2_P5ylz", "chain i and " + object_name)
        cmd.extract("SMX3_1_P5ylz", "chain c and " + object_name)
        cmd.extract("SMX3_2_P5ylz", "chain j and " + object_name)
        cmd.extract("SMX2_1_P5ylz", "chain d and " + object_name)
        cmd.extract("SMX2_2_P5ylz", "chain k and " + object_name)
        cmd.extract("SMD3_1_P5ylz", "chain e and " + object_name)
        cmd.extract("SMD3_2_P5ylz", "chain l and " + object_name)
        cmd.extract("SMD1_1_P5ylz", "chain f and " + object_name)
        cmd.extract("SMD1_2_P5ylz", "chain m and " + object_name)
        cmd.extract("SMD2_1_P5ylz", "chain g and " + object_name)
        cmd.extract("SMD2_2_P5ylz", "chain n and " + object_name)
        cmd.extract("PRP22_P5ylz", "chain W and " + object_name)
        cmd.extract("PRP18_P5ylz", "chain U and " + object_name)
        cmd.extract("SLU7_P5ylz", "chain V and " + object_name)
        cmd.set_name(object_name, "unknown_other_P5ylz")
        cmd.group("P5ylz", "*_P5ylz")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5y88' in n:
            object_name = n
            print(object_name)
            
    if '5y88' in name.lower():
        cmd.extract("PRP8_I5y88", "chain A and " + object_name)
        cmd.extract("BUD31_I5y88", "chain L and " + object_name)
        cmd.extract("CLF1_I5y88", "chain I and " + object_name)
        cmd.extract("CWC15_I5y88", "chain P and " + object_name)
        cmd.extract("CWC16/YJU2_I5y88", "chain R and " + object_name)
        cmd.extract("CWC2_hRBM22_I5y88", "chain N and " + object_name)
        cmd.extract("CWC25_I5y88", "chain G and " + object_name)
        cmd.extract("Intron_2_I5y88", "chain E and " + object_name)
        cmd.extract("LEA1_I5y88", "chain o and " + object_name)
        cmd.extract("Msl1_I5y88", "chain p and " + object_name)
        cmd.extract("PRP45_I5y88", "chain Q and " + object_name)
        cmd.extract("CDC40_I5y88", "chain S and " + object_name)
        cmd.extract("PRP19_1_I5y88", "chain q and " + object_name)
        cmd.extract("PRP19_2_I5y88", "chain r and " + object_name)
        cmd.extract("PRP19_3_I5y88", "chain s and " + object_name)
        cmd.extract("PRP19_4_I5y88", "chain t and " + object_name)
        cmd.extract("PRP46_I5y88", "chain O and " + object_name)
        cmd.extract("SLT11/ECM2_I5y88", "chain M and " + object_name)
        cmd.extract("SNT309_I5y88", "chain G and " + object_name)
        cmd.extract("SNU114_I5y88", "chain C and " + object_name)
        cmd.extract("SYF2_I5y88", "chain K and " + object_name)
        cmd.extract("SYF1_I5y88", "chain H and " + object_name)
        cmd.extract("U2_I5y88", "chain F and " + object_name)
        cmd.extract("U5_I5y88", "chain B and " + object_name)
        cmd.extract("U6_I5y88", "chain D and " + object_name)
        cmd.extract("Intron_I5y88", "chain x and " + object_name)
        cmd.extract("RNA_I5y88", "chain x and " + object_name)
        cmd.extract("cwc23_I5y88", "chain T and " + object_name)
        cmd.extract("SPP382_I5y88", "chain U and " + object_name)
        cmd.extract("NTR2_I5y88", "chain V and " + object_name)
        cmd.extract("PRP43_I5y88", "chain W and " + object_name)
        cmd.extract("SMB1_1_I5y88", "chain a and " + object_name)
        cmd.extract("SMB1_2_I5y88", "chain h and " + object_name)
        cmd.extract("SME1_1_I5y88", "chain b and " + object_name)
        cmd.extract("SME1_2_I5y88", "chain i and " + object_name)
        cmd.extract("SMX3_1_I5y88", "chain c and " + object_name)
        cmd.extract("SMX3_2_I5y88", "chain j and " + object_name)
        cmd.extract("SMX2_1_I5y88", "chain d and " + object_name)
        cmd.extract("SMX2_2_I5y88", "chain k and " + object_name)
        cmd.extract("SMD3_1_I5y88", "chain e and " + object_name)
        cmd.extract("SMD3_2_I5y88", "chain l and " + object_name)
        cmd.extract("SMD1_1_I5y88", "chain f and " + object_name)
        cmd.extract("SMD1_2_I5y88", "chain m and " + object_name)
        cmd.extract("SMD2_1_I5y88", "chain g and " + object_name)
        cmd.extract("SMD2_2_I5y88", "chain n and " + object_name)
        cmd.set_name(object_name, "unknown_other_I5y88")
        cmd.group("I5y88", "*_I5y88")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '3jb9' in n:
            object_name = n
            print(object_name)
            
    if '3jb9' in name.lower():
        cmd.extract("U2_3jb9", "chain P and " + object_name)
        cmd.extract("U5_3jb9", "chain C and " + object_name)
        cmd.extract("U6_3jb9", "chain N and " + object_name)
        cmd.extract("Intron_1_3jb9", "chain O and " + object_name)
        cmd.extract("Intron_2_3jb9", "chain Q and " + object_name)
        cmd.extract("Spp42_yPrp8_3jb9", "chain A and " + object_name)
        cmd.extract("CWF15_yCWC15_3jb9", "chain h and " + object_name)
        cmd.set_name(object_name, "unknown_other_3jb9")
        cmd.group("3jb9", "*_3jb9")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6icz' in n:
            object_name = n
            print(object_name)
            
    if '6icz' in name.lower():
        cmd.extract("CWC15_hP_6icz", "chain P and " + object_name)
        cmd.extract("U2_hP_6icz", "chain H and " + object_name)
        cmd.extract("U5_hP_6icz", "chain B and " + object_name)
        cmd.extract("U6_hP_6icz", "chain F and " + object_name)
        cmd.extract("Intron_hP_6icz", "chain G and " + object_name)
        cmd.extract("cwc23_hP_6icz", "chain 6ICZ and " + object_name)
        cmd.set_name(object_name, "unknown_other_hP_6icz")
        cmd.group("hP_6icz", "*_hP_6icz")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6ff7' in n:
            object_name = n
            print(object_name)
            
    if '6ff7' in name.lower():
        cmd.extract("CWC15_hBa_6ff7", "chain R and " + object_name)
        cmd.extract("CWC2_hRBM22_hBa_6ff7", "chain P and " + object_name)
        cmd.extract("U2_hBa_6ff7", "chain 2 and " + object_name)
        cmd.extract("U5_hBa_6ff7", "chain 5 and " + object_name)
        cmd.extract("U6_hBa_6ff7", "chain 6 and " + object_name)
        cmd.extract("Intron_hBa_6ff7", "chain Z and " + object_name)
        cmd.set_name(object_name, "unknown_other_hBa_6ff7")
        cmd.group("hBa_6ff7", "*_hBa_6ff7")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5yzg' in n:
            object_name = n
            print(object_name)
            
    if '5yzg' in name.lower():
        cmd.extract("CWC15_hC_5yzg", "chain P and " + object_name)
        cmd.extract("CWC2_hRBM22_hC_5yzg", "chain O and " + object_name)
        cmd.extract("CWC25_hC_5yzg", "chain X and " + object_name)
        cmd.extract("PRP16_hDHX38_hC_5yzg", "chain Z and " + object_name)
        cmd.extract("U2_hC_5yzg", "chain H and " + object_name)
        cmd.extract("U5_hC_5yzg", "chain B and " + object_name)
        cmd.extract("U6_hC_5yzg", "chain F and " + object_name)
        cmd.extract("Intron_hC_5yzg", "chain G and " + object_name)
        cmd.set_name(object_name, "unknown_other_hC_5yzg")
        cmd.group("hC_5yzg", "*_hC_5yzg")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5xjc' in n:
            object_name = n
            print(object_name)
            
    if '5xjc' in name.lower():
        cmd.extract("CWC15_hX_5xjc", "chain P and " + object_name)
        cmd.extract("CWC25_hX_5xjc", "chain X and " + object_name)
        cmd.extract("U2_hX_5xjc", "chain H and " + object_name)
        cmd.extract("U5_hX_5xjc", "chain B and " + object_name)
        cmd.extract("U6_hX_5xjc", "chain F and " + object_name)
        cmd.extract("Intron_hX_5xjc", "chain G and " + object_name)
        cmd.extract("PRKRIP1_hX_5xjc", "chain X and " + object_name)
        cmd.set_name(object_name, "unknown_other_hX_5xjc")
        cmd.group("hX_5xjc", "*_hX_5xjc")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '5gan' in n:
            object_name = n
            print(object_name)
            
    if '5gan' in name.lower():
        cmd.extract("PRP8_y3_5gan", "chain A and " + object_name)
        cmd.extract("BRR2_y3_5gan", "chain B and " + object_name)
        cmd.extract("PRP45_y3_5gan", "chain H and " + object_name)
        cmd.extract("SNU114_y3_5gan", "chain C and " + object_name)
        cmd.extract("U5_y3_5gan", "chain U and " + object_name)
        cmd.extract("U6_y3_5gan", "chain W and " + object_name)
        cmd.extract("U4_y3_5gan", "chain V and " + object_name)
        cmd.extract("PRP31_y3_5gan", "chain F and " + object_name)
        cmd.extract("PRP6_y3_5gan", "chain J and " + object_name)
        cmd.extract("PRP3_y3_5gan", "chain G and " + object_name)
        cmd.extract("DIB1_y3_5gan", "chain D and " + object_name)
        cmd.extract("SNU13_y3_5gan", "chain K and " + object_name)
        cmd.extract("LSM8_y3_5gan", "chain 8 and " + object_name)
        cmd.extract("LSM2_y3_5gan", "chain 2 and " + object_name)
        cmd.extract("LSM3_y3_5gan", "chain 3 and " + object_name)
        cmd.extract("LSM6_y3_5gan", "chain 6 and " + object_name)
        cmd.extract("LSM5_y3_5gan", "chain 5 and " + object_name)
        cmd.extract("LSM7_y3_5gan", "chain 7 and " + object_name)
        cmd.extract("LSM4_y3_5gan", "chain 4 and " + object_name)
        cmd.extract("SNU66_y3_5gan", "chain E and " + object_name)
        cmd.extract("SMB1_1_y3_5gan", "chain b and " + object_name)
        cmd.extract("SMB1_2_y3_5gan", "chain k and " + object_name)
        cmd.extract("SME1_1_y3_5gan", "chain e and " + object_name)
        cmd.extract("SME1_2_y3_5gan", "chain p and " + object_name)
        cmd.extract("SMX3_1_y3_5gan", "chain f and " + object_name)
        cmd.extract("SMX3_2_y3_5gan", "chain q and " + object_name)
        cmd.extract("SMX2_1_y3_5gan", "chain g and " + object_name)
        cmd.extract("SMX2_2_y3_5gan", "chain r and " + object_name)
        cmd.extract("SMD3_1_y3_5gan", "chain d and " + object_name)
        cmd.extract("SMD3_2_y3_5gan", "chain n and " + object_name)
        cmd.extract("SMD1_1_y3_5gan", "chain h and " + object_name)
        cmd.extract("SMD1_2_y3_5gan", "chain l and " + object_name)
        cmd.extract("SMD2_1_y3_5gan", "chain j and " + object_name)
        cmd.extract("SMD2_2_y3_5gan", "chain m and " + object_name)
        cmd.extract("unassigned_y3_5gan", "chain X and " + object_name)
        cmd.set_name(object_name, "unknown_other_y3_5gan")
        cmd.group("y3_5gan", "*_y3_5gan")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6qw6' in n:
            object_name = n
            print(object_name)
            
    if '6qw6' in name.lower():
        cmd.extract("PRP8_h3_6qw6", "chain 5A and " + object_name)
        cmd.extract("U5_h3_6qw6", "chain 5 and " + object_name)
        cmd.extract("U6_h3_6qw6", "chain 6 and " + object_name)
        cmd.extract("U4_h3_6qw6", "chain 4 and " + object_name)
        cmd.extract("Prp28_h3_6qw6", "chain 5X and " + object_name)
        cmd.set_name(object_name, "unknown_other_h3_6qw6")
        cmd.group("h3_6qw6", "*_h3_6qw6")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '3jcr' in n:
            object_name = n
            print(object_name)
            
    if '3jcr' in name.lower():
        cmd.extract("PRP8_h3_3jcr", "chain A and " + object_name)
        cmd.extract("BRR2_h3_3jcr", "chain C and " + object_name)
        cmd.extract("SNU114_h3_3jcr", "chain B and " + object_name)
        cmd.extract("U5_h3_3jcr", "chain H and " + object_name)
        cmd.extract("U6_h3_3jcr", "chain N and " + object_name)
        cmd.extract("U4_h3_3jcr", "chain M and " + object_name)
        cmd.extract("PRP4_h3_3jcr", "chain L and " + object_name)
        cmd.extract("PRP31_h3_3jcr", "chain J and " + object_name)
        cmd.extract("PRP6_h3_3jcr", "chain G and " + object_name)
        cmd.extract("PRP3_h3_3jcr", "chain K and " + object_name)
        cmd.extract("SNU13_h3_3jcr", "chain I and " + object_name)
        cmd.extract("LSM8_h3_3jcr", "chain 8 and " + object_name)
        cmd.extract("LSM2_h3_3jcr", "chain 2 and " + object_name)
        cmd.extract("LSM3_h3_3jcr", "chain 3 and " + object_name)
        cmd.extract("LSM5_h3_3jcr", "chain 5 and " + object_name)
        cmd.extract("LSM7_h3_3jcr", "chain 7 and " + object_name)
        cmd.extract("LSM4_h3_3jcr", "chain 4 and " + object_name)
        cmd.extract("SMD3_1_h3_3jcr", "chain R and " + object_name)
        cmd.extract("SMD3_2_h3_3jcr", "chain r and " + object_name)
        cmd.extract("SMD1_1_h3_3jcr", "chain P and " + object_name)
        cmd.extract("SMD1_2_h3_3jcr", "chain p and " + object_name)
        cmd.extract("SMD2_1_h3_3jcr", "chain Q and " + object_name)
        cmd.extract("SMD2_2_h3_3jcr", "chain q and " + object_name)
        cmd.extract("U5-40K_h3_3jcr", "chain D and " + object_name)
        cmd.extract("Dim1_h3_3jcr", "chain E and " + object_name)
        cmd.extract("Prp28_h3_3jcr", "chain F and " + object_name)
        cmd.extract("SmE_1_h3_3jcr", "chain S and " + object_name)
        cmd.extract("SmE_2_h3_3jcr", "chain s and " + object_name)
        cmd.extract("SmF_1_h3_3jcr", "chain T and " + object_name)
        cmd.extract("SmF_2_h3_3jcr", "chain t and " + object_name)
        cmd.extract("SmG_1_h3_3jcr", "chain U and " + object_name)
        cmd.extract("SmG_2_h3_3jcr", "chain u and " + object_name)
        cmd.extract("Sad1_h3_3jcr", "chain V and " + object_name)
        cmd.extract("SmB_1_h3_3jcr", "chain O and " + object_name)
        cmd.extract("SmB_2_h3_3jcr", "chain o and " + object_name)
        cmd.set_name(object_name, "unknown_other_h3_3jcr")
        cmd.group("h3_3jcr", "*_h3_3jcr")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6qx9' in n:
            object_name = n
            print(object_name)
            
    if '6qx9' in name.lower():
        cmd.extract("PRP8_h3_6qx9", "chain 5A and " + object_name)
        cmd.extract("U2_h3_6qx9", "chain 2 and " + object_name)
        cmd.extract("U5_h3_6qx9", "chain 5 and " + object_name)
        cmd.extract("U6_h3_6qx9", "chain 6 and " + object_name)
        cmd.extract("U4_h3_6qx9", "chain 4 and " + object_name)
        cmd.extract("Intron_h3_6qx9", "chain I and " + object_name)
        cmd.extract("U1_h3_6qx9", "chain 1 and " + object_name)
        cmd.extract("Prp28_h3_6qx9", "chain 5X and " + object_name)
        cmd.set_name(object_name, "unknown_other_h3_6qx9")
        cmd.group("h3_6qx9", "*_h3_6qx9")
        cmd.do("order *, yes")
    
    for n in cmd.get_names("all"):
        if '6ah0' in n:
            object_name = n
            print(object_name)
            
    if '6ah0' in name.lower():
        cmd.extract("PRP8_h_Bp_6ah0", "chain A and " + object_name)
        cmd.extract("U2_h_Bp_6ah0", "chain H and " + object_name)
        cmd.extract("U5_h_Bp_6ah0", "chain B and " + object_name)
        cmd.extract("U6_h_Bp_6ah0", "chain F and " + object_name)
        cmd.extract("U4_h_Bp_6ah0", "chain I and " + object_name)
        cmd.extract("Intron_h_Bp_6ah0", "chain G and " + object_name)
        cmd.extract("Prp28_h_Bp_6ah0", "chain X and " + object_name)
        cmd.set_name(object_name, "unknown_other_h_Bp_6ah0")
        cmd.group("h_Bp_6ah0", "*_h_Bp_6ah0")
        cmd.do("order *, yes")
