
try:
    from pymol import cmd
except ImportError:
    print("PyMOL Python lib is missing")
    # sys.exit(0)

def spl_extract():
 for name in cmd.get_names("all"):
  if name in : ['5gm6', '5zwo', '5lj3', '5gm6', '5mps', '6exn', '5ylz', '5y88']# this should be auto
    print(" \ Extracting mode for %s" % name)
    if '5zwo' in name.lower():
        cmd.extract("PRP8_B5zwo", "chain A and 5zwo")
        cmd.extract("BRR2_B5zwo", "chain D and 5zwo")
        cmd.extract("LEA1_B5zwo", "chain o and 5zwo")
        cmd.extract("Msl1_B5zwo", "chain p and 5zwo")
        cmd.extract("SNU114_B5zwo", "chain C and 5zwo")
        cmd.extract("U2_B5zwo", "chain H and 5zwo")
        cmd.extract("U5_B5zwo", "chain B and 5zwo")
        cmd.extract("U6_B5zwo", "chain F and 5zwo")
        cmd.extract("U4_B5zwo", "chain I and 5zwo")
        cmd.extract("Intron_B5zwo", "chain G and 5zwo")
        cmd.extract("PRP4_B5zwo", "chain K and 5zwo")
        cmd.extract("PRP31_B5zwo", "chain L and 5zwo")
        cmd.extract("PRP6_B5zwo", "chain N and 5zwo")
        cmd.extract("PRP3_B5zwo", "chain J and 5zwo")
        cmd.extract("DIB1_B5zwo", "chain E and 5zwo")
        cmd.extract("SNU13_B5zwo", "chain M and 5zwo")
        cmd.extract("LSM8_B5zwo", "chain z and 5zwo")
        cmd.extract("LSM2_B5zwo", "chain q and 5zwo")
        cmd.extract("LSM3_B5zwo", "chain r and 5zwo")
        cmd.extract("LSM6_B5zwo", "chain x and 5zwo")
        cmd.extract("LSM5_B5zwo", "chain t and 5zwo")
        cmd.extract("LSM7_B5zwo", "chain y and 5zwo")
        cmd.extract("LSM4_B5zwo", "chain s and 5zwo")
        cmd.extract("SNU66_B5zwo", "chain O and 5zwo")
        cmd.extract("BUD13_B5zwo", "chain Y and 5zwo")
        cmd.extract("Cus1_B5zwo", "chain 2 and 5zwo")
        cmd.extract("HSH155_B5zwo", "chain 1 and 5zwo")
        cmd.extract("HSH49_B5zwo", "chain 4 and 5zwo")
        cmd.extract("PML1_B5zwo", "chain Z and 5zwo")
        cmd.extract("PRP11_B5zwo", "chain v and 5zwo")
        cmd.extract("RDS3_B5zwo", "chain 5 and 5zwo")
        cmd.extract("RSE1_B5zwo", "chain 3 and 5zwo")
        cmd.extract("SNU17_B5zwo", "chain X and 5zwo")
        cmd.extract("Ysf3_B5zwo", "chain 6 and 5zwo")
        cmd.extract("SMB1_1_B5zwo", "chain a and 5zwo")
        cmd.extract("SMB1_2_B5zwo", "chain P and 5zwo")
        cmd.extract("SMB1_3_B5zwo", "chain h and 5zwo")
        cmd.extract("SME1_1_B5zwo", "chain e and 5zwo")
        cmd.extract("SME1_2_B5zwo", "chain T and 5zwo")
        cmd.extract("SME1_3_B5zwo", "chain i and 5zwo")
        cmd.extract("SMX3_1_B5zwo", "chain f and 5zwo")
        cmd.extract("SMX3_2_B5zwo", "chain U and 5zwo")
        cmd.extract("SMX3_3_B5zwo", "chain j and 5zwo")
        cmd.extract("SMX2_1_B5zwo", "chain g and 5zwo")
        cmd.extract("SMX2_2_B5zwo", "chain V and 5zwo")
        cmd.extract("SMX2_3_B5zwo", "chain k and 5zwo")
        cmd.extract("SMD3_1_B5zwo", "chain d and 5zwo")
        cmd.extract("SMD3_2_B5zwo", "chain S and 5zwo")
        cmd.extract("SMD3_3_B5zwo", "chain l and 5zwo")
        cmd.extract("SMD1_1_B5zwo", "chain b and 5zwo")
        cmd.extract("SMD1_2_B5zwo", "chain Q and 5zwo")
        cmd.extract("SMD1_3_B5zwo", "chain m and 5zwo")
        cmd.extract("SMD2_1_B5zwo", "chain c and 5zwo")
        cmd.extract("SMD2_2_B5zwo", "chain R and 5zwo")
        cmd.extract("SMD2_3_B5zwo", "chain n and 5zwo")
        cmd.extract("PRP9_B5zwo", "chain u and 5zwo")
        cmd.extract("PRP21_B5zwo", "chain w and 5zwo")
        cmd.extract("SNU23_B5zwo", "chain W and 5zwo")
        cmd.extract("PRP38_B5zwo", "chain 0 and 5zwo")
        cmd.extract("SPP381_B5zwo", "chain 9 and 5zwo")
        cmd.set_name("5zwo", "unknown_B5zwo")
        cmd.group("B5zwo", "*_B5zwo")
        cmd.do("order *, yes")
    if '5gm6' in name.lower():
        cmd.extract("PRP8_Ba5gm6", "chain A and 5gm6")
        cmd.extract("BRR2_Ba5gm6", "chain B and 5gm6")
        cmd.extract("BUD31_Ba5gm6", "chain T and 5gm6")
        cmd.extract("CEF1_Ba5gm6", "chain c and 5gm6")
        cmd.extract("CWC15_Ba5gm6", "chain S and 5gm6")
        cmd.extract("CWC2_Ba5gm6", "chain R and 5gm6")
        cmd.extract("CWC21_Ba5gm6", "chain X and 5gm6")
        cmd.extract("CWC22_Ba5gm6", "chain Z and 5gm6")
        cmd.extract("PRP45_Ba5gm6", "chain P and 5gm6")
        cmd.extract("CDC40_Ba5gm6", "chain n and 5gm6")
        cmd.extract("PRP19_Ba5gm6", "chain f and 5gm6")
        cmd.extract("PRP46_Ba5gm6", "chain O and 5gm6")
        cmd.extract("SLT11/ECM2_Ba5gm6", "chain Q and 5gm6")
        cmd.extract("SNT309_Ba5gm6", "chain t and 5gm6")
        cmd.extract("SNU114_Ba5gm6", "chain C and 5gm6")
        cmd.extract("SYF2_Ba5gm6", "chain f and 5gm6")
        cmd.extract("SYF1_Ba5gm6", "chain v and 5gm6")
        cmd.extract("U2_Ba5gm6", "chain L and 5gm6")
        cmd.extract("U5_Ba5gm6", "chain 5 and 5gm6")
        cmd.extract("U6_Ba5gm6", "chain 6 and 5gm6")
        cmd.extract("Intron_Ba5gm6", "chain M and 5gm6")
        cmd.extract("Exon_Ba5gm6", "chain N and 5gm6")
        cmd.extract("BUD13_Ba5gm6", "chain W and 5gm6")
        cmd.extract("CLF2_Ba5gm6", "chain d and 5gm6")
        cmd.extract("Cus1_Ba5gm6", "chain H and 5gm6")
        cmd.extract("CWC24_Ba5gm6", "chain a and 5gm6")
        cmd.extract("CWC27_Ba5gm6", "chain b and 5gm6")
        cmd.extract("HSH155_Ba5gm6", "chain G and 5gm6")
        cmd.extract("HSH49_Ba5gm6", "chain e and 5gm6")
        cmd.extract("PML1_Ba5gm6", "chain U and 5gm6")
        cmd.extract("PRP11_Ba5gm6", "chain I and 5gm6")
        cmd.extract("PRP2_Ba5gm6", "chain Y and 5gm6")
        cmd.extract("RDS3_Ba5gm6", "chain J and 5gm6")
        cmd.extract("RSE1_Ba5gm6", "chain F and 5gm6")
        cmd.extract("SNU17_Ba5gm6", "chain V and 5gm6")
        cmd.extract("Ysf3_Ba5gm6", "chain K and 5gm6")
        cmd.set_name("5gm6", "unknown_Ba5gm6")
        cmd.group("Ba5gm6", "*_Ba5gm6")
        cmd.do("order *, yes")
    if '5lj3' in name.lower():
        cmd.extract("PRP8_C5lj3", "chain A and 5lj3")
        cmd.extract("BUD31_C5lj3", "chain L and 5lj3")
        cmd.extract("CEF1_C5lj3", "chain O and 5lj3")
        cmd.extract("CLF1_C5lj3", "chain S and 5lj3")
        cmd.extract("CWC15_C5lj3", "chain P and 5lj3")
        cmd.extract("CWC16/YJU2_C5lj3", "chain D and 5lj3")
        cmd.extract("CWC2_C5lj3", "chain M and 5lj3")
        cmd.extract("CWC21_C5lj3", "chain R and 5lj3")
        cmd.extract("CWC22_C5lj3", "chain H and 5lj3")
        cmd.extract("CWC25_C5lj3", "chain F and 5lj3")
        cmd.extract("ISY1_C5lj3", "chain G and 5lj3")
        cmd.extract("LEA1_C5lj3", "chain W and 5lj3")
        cmd.extract("Msl1_C5lj3", "chain Y and 5lj3")
        cmd.extract("PRP45_C5lj3", "chain K and 5lj3")
        cmd.extract("PRP46_C5lj3", "chain J and 5lj3")
        cmd.extract("SLT11/ECM2_C5lj3", "chain N and 5lj3")
        cmd.extract("SNU114_C5lj3", "chain C and 5lj3")
        cmd.extract("SYF1_C5lj3", "chain T and 5lj3")
        cmd.extract("U2_C5lj3", "chain Z and 5lj3")
        cmd.extract("U5_C5lj3", "chain U and 5lj3")
        cmd.extract("U6_C5lj3", "chain V and 5lj3")
        cmd.extract("Intron_C5lj3", "chain I and 5lj3")
        cmd.extract("Exon_C5lj3", "chain E and 5lj3")
        cmd.extract("SMB1_1_C5lj3", "chain b and 5lj3")
        cmd.extract("SMB1_2_C5lj3", "chain k and 5lj3")
        cmd.extract("SME1_1_C5lj3", "chain e and 5lj3")
        cmd.extract("SME1_2_C5lj3", "chain p and 5lj3")
        cmd.extract("SMX3_1_C5lj3", "chain f and 5lj3")
        cmd.extract("SMX3_2_C5lj3", "chain q and 5lj3")
        cmd.extract("SMX2_1_C5lj3", "chain g and 5lj3")
        cmd.extract("SMX2_2_C5lj3", "chain r and 5lj3")
        cmd.extract("SMD3_1_C5lj3", "chain d and 5lj3")
        cmd.extract("SMD3_2_C5lj3", "chain n and 5lj3")
        cmd.extract("SMD1_1_C5lj3", "chain h and 5lj3")
        cmd.extract("SMD1_2_C5lj3", "chain l and 5lj3")
        cmd.extract("SMD2_1_C5lj3", "chain j and 5lj3")
        cmd.extract("SMD2_2_C5lj3", "chain m and 5lj3")
        cmd.set_name("5lj3", "unknown_C5lj3")
        cmd.group("C5lj3", "*_C5lj3")
        cmd.do("order *, yes")
    if '5mps' in name.lower():
        cmd.extract("PRP8_Cs5mps", "chain A and 5mps")
        cmd.extract("BUD31_Cs5mps", "chain L and 5mps")
        cmd.extract("CEF1_Cs5mps", "chain O and 5mps")
        cmd.extract("CLF1_Cs5mps", "chain S and 5mps")
        cmd.extract("CWC15_Cs5mps", "chain P and 5mps")
        cmd.extract("CWC2_Cs5mps", "chain M and 5mps")
        cmd.extract("CWC21_Cs5mps", "chain R and 5mps")
        cmd.extract("CWC22_Cs5mps", "chain H and 5mps")
        cmd.extract("PRP45_Cs5mps", "chain K and 5mps")
        cmd.extract("CDC40_Cs5mps", "chain o and 5mps")
        cmd.extract("PRP46_Cs5mps", "chain J and 5mps")
        cmd.extract("SLT11/ECM2_Cs5mps", "chain N and 5mps")
        cmd.extract("SNU114_Cs5mps", "chain C and 5mps")
        cmd.extract("SYF2_Cs5mps", "chain y and 5mps")
        cmd.extract("SYF1_Cs5mps", "chain T and 5mps")
        cmd.extract("U2_Cs5mps", "chain 2 and 5mps")
        cmd.extract("U5_Cs5mps", "chain 5 and 5mps")
        cmd.extract("U6_Cs5mps", "chain 6 and 5mps")
        cmd.extract("5EXON_Cs5mps", "chain E and 5mps")
        cmd.extract("Intron_Cs5mps", "chain I and 5mps")
        cmd.extract("Exon_Cs5mps", "chain E and 5mps")
        cmd.extract("SMB1_Cs5mps", "chain b and 5mps")
        cmd.extract("SME1_Cs5mps", "chain e and 5mps")
        cmd.extract("SMX3_Cs5mps", "chain f and 5mps")
        cmd.extract("SMX2_Cs5mps", "chain g and 5mps")
        cmd.extract("SMD3_Cs5mps", "chain d and 5mps")
        cmd.extract("SMD1_Cs5mps", "chain h and 5mps")
        cmd.extract("SMD2_Cs5mps", "chain j and 5mps")
        cmd.extract("PRP18_Cs5mps", "chain a and 5mps")
        cmd.extract("SLU7_Cs5mps", "chain c and 5mps")
        cmd.set_name("5mps", "unknown_Cs5mps")
        cmd.group("Cs5mps", "*_Cs5mps")
        cmd.do("order *, yes")
    if '6exn' in name.lower():
        cmd.extract("PRP8_P6exn", "chain A and 6exn")
        cmd.extract("BUD31_P6exn", "chain L and 6exn")
        cmd.extract("CEF1_P6exn", "chain O and 6exn")
        cmd.extract("CLF1_P6exn", "chain S and 6exn")
        cmd.extract("CWC15_P6exn", "chain P and 6exn")
        cmd.extract("CWC16/YJU2_P6exn", "chain D and 6exn")
        cmd.extract("CWC2_P6exn", "chain M and 6exn")
        cmd.extract("CWC21_P6exn", "chain R and 6exn")
        cmd.extract("CWC22_P6exn", "chain H and 6exn")
        cmd.extract("LEA1_P6exn", "chain W and 6exn")
        cmd.extract("Msl1_P6exn", "chain Y and 6exn")
        cmd.extract("PRP45_P6exn", "chain K and 6exn")
        cmd.extract("CDC40_P6exn", "chain o and 6exn")
        cmd.extract("PRP19_1_P6exn", "chain t and 6exn")
        cmd.extract("PRP19_2_P6exn", "chain u and 6exn")
        cmd.extract("PRP19_3_P6exn", "chain v and 6exn")
        cmd.extract("PRP19_4_P6exn", "chain w and 6exn")
        cmd.extract("PRP46_P6exn", "chain J and 6exn")
        cmd.extract("SLT11/ECM2_P6exn", "chain N and 6exn")
        cmd.extract("SNU114_P6exn", "chain C and 6exn")
        cmd.extract("SYF1_P6exn", "chain T and 6exn")
        cmd.extract("U2_P6exn", "chain 2 and 6exn")
        cmd.extract("U5_P6exn", "chain 5 and 6exn")
        cmd.extract("U6_P6exn", "chain 6 and 6exn")
        cmd.extract("Intron_P6exn", "chain I and 6exn")
        cmd.extract("Exon_P6exn", "chain E and 6exn")
        cmd.extract("SMB1_1_P6exn", "chain b and 6exn")
        cmd.extract("SMB1_2_P6exn", "chain k and 6exn")
        cmd.extract("SME1_1_P6exn", "chain e and 6exn")
        cmd.extract("SME1_2_P6exn", "chain p and 6exn")
        cmd.extract("SMX3_1_P6exn", "chain f and 6exn")
        cmd.extract("SMX3_2_P6exn", "chain q and 6exn")
        cmd.extract("SMX2_1_P6exn", "chain g and 6exn")
        cmd.extract("SMX2_2_P6exn", "chain r and 6exn")
        cmd.extract("SMD3_1_P6exn", "chain d and 6exn")
        cmd.extract("SMD3_2_P6exn", "chain n and 6exn")
        cmd.extract("SMD1_1_P6exn", "chain h and 6exn")
        cmd.extract("SMD1_2_P6exn", "chain l and 6exn")
        cmd.extract("SMD2_1_P6exn", "chain j and 6exn")
        cmd.extract("SMD2_2_P6exn", "chain m and 6exn")
        cmd.extract("PRP22_P6exn", "chain V and 6exn")
        cmd.extract("PRP18_P6exn", "chain a and 6exn")
        cmd.extract("SLU7_P6exn", "chain c and 6exn")
        cmd.set_name("6exn", "unknown_P6exn")
        cmd.group("P6exn", "*_P6exn")
        cmd.do("order *, yes")
    if '5ylz' in name.lower():
        cmd.extract("PRP8_P5ylz", "chain A and 5ylz")
        cmd.extract("BUD31_P5ylz", "chain L and 5ylz")
        cmd.extract("CEF1_P5ylz", "chain J and 5ylz")
        cmd.extract("CLF1_P5ylz", "chain I and 5ylz")
        cmd.extract("CWC15_P5ylz", "chain P and 5ylz")
        cmd.extract("CWC2_P5ylz", "chain N and 5ylz")
        cmd.extract("CWC21_P5ylz", "chain R and 5ylz")
        cmd.extract("CWC22_P5ylz", "chain S and 5ylz")
        cmd.extract("LEA1_P5ylz", "chain o and 5ylz")
        cmd.extract("Msl1_P5ylz", "chain p and 5ylz")
        cmd.extract("PRP45_P5ylz", "chain Q and 5ylz")
        cmd.extract("CDC40_P5ylz", "chain T and 5ylz")
        cmd.extract("PRP19_1_P5ylz", "chain q and 5ylz")
        cmd.extract("PRP19_2_P5ylz", "chain r and 5ylz")
        cmd.extract("PRP19_3_P5ylz", "chain s and 5ylz")
        cmd.extract("PRP19_4_P5ylz", "chain t and 5ylz")
        cmd.extract("PRP46_P5ylz", "chain O and 5ylz")
        cmd.extract("SLT11/ECM2_P5ylz", "chain M and 5ylz")
        cmd.extract("SNT309_P5ylz", "chain G and 5ylz")
        cmd.extract("SNU114_P5ylz", "chain C and 5ylz")
        cmd.extract("SYF2_P5ylz", "chain K and 5ylz")
        cmd.extract("SYF1_P5ylz", "chain H and 5ylz")
        cmd.extract("U2_P5ylz", "chain F and 5ylz")
        cmd.extract("U5_P5ylz", "chain B and 5ylz")
        cmd.extract("U6_P5ylz", "chain D and 5ylz")
        cmd.extract("Intron_P5ylz", "chain E and 5ylz")
        cmd.extract("SMB1_1_P5ylz", "chain a and 5ylz")
        cmd.extract("SMB1_2_P5ylz", "chain h and 5ylz")
        cmd.extract("SME1_1_P5ylz", "chain b and 5ylz")
        cmd.extract("SME1_2_P5ylz", "chain i and 5ylz")
        cmd.extract("SMX3_1_P5ylz", "chain c and 5ylz")
        cmd.extract("SMX3_2_P5ylz", "chain j and 5ylz")
        cmd.extract("SMX2_1_P5ylz", "chain d and 5ylz")
        cmd.extract("SMX2_2_P5ylz", "chain k and 5ylz")
        cmd.extract("SMD3_1_P5ylz", "chain e and 5ylz")
        cmd.extract("SMD3_2_P5ylz", "chain l and 5ylz")
        cmd.extract("SMD1_1_P5ylz", "chain f and 5ylz")
        cmd.extract("SMD1_2_P5ylz", "chain m and 5ylz")
        cmd.extract("SMD2_1_P5ylz", "chain g and 5ylz")
        cmd.extract("SMD2_2_P5ylz", "chain n and 5ylz")
        cmd.extract("PRP22_P5ylz", "chain W and 5ylz")
        cmd.extract("PRP18_P5ylz", "chain U and 5ylz")
        cmd.extract("SLU7_P5ylz", "chain V and 5ylz")
        cmd.set_name("5ylz", "unknown_P5ylz")
        cmd.group("P5ylz", "*_P5ylz")
        cmd.do("order *, yes")
    if '5y88' in name.lower():
        cmd.extract("PRP8_I5y88", "chain A and 5y88")
        cmd.extract("BUD31_I5y88", "chain L and 5y88")
        cmd.extract("CLF1_I5y88", "chain I and 5y88")
        cmd.extract("CWC15_I5y88", "chain P and 5y88")
        cmd.extract("CWC16/YJU2_I5y88", "chain R and 5y88")
        cmd.extract("CWC2_I5y88", "chain N and 5y88")
        cmd.extract("CWC25_I5y88", "chain G and 5y88")
        cmd.extract("Intron_2_I5y88", "chain E and 5y88")
        cmd.extract("LEA1_I5y88", "chain o and 5y88")
        cmd.extract("Msl1_I5y88", "chain p and 5y88")
        cmd.extract("PRP45_I5y88", "chain Q and 5y88")
        cmd.extract("CDC40_I5y88", "chain S and 5y88")
        cmd.extract("PRP19_1_I5y88", "chain q and 5y88")
        cmd.extract("PRP19_2_I5y88", "chain r and 5y88")
        cmd.extract("PRP19_3_I5y88", "chain s and 5y88")
        cmd.extract("PRP19_4_I5y88", "chain t and 5y88")
        cmd.extract("PRP46_I5y88", "chain O and 5y88")
        cmd.extract("SLT11/ECM2_I5y88", "chain M and 5y88")
        cmd.extract("SNT309_I5y88", "chain G and 5y88")
        cmd.extract("SNU114_I5y88", "chain C and 5y88")
        cmd.extract("SYF2_I5y88", "chain K and 5y88")
        cmd.extract("SYF1_I5y88", "chain H and 5y88")
        cmd.extract("U2_I5y88", "chain F and 5y88")
        cmd.extract("U5_I5y88", "chain B and 5y88")
        cmd.extract("U6_I5y88", "chain D and 5y88")
        cmd.extract("Intron_I5y88", "chain x and 5y88")
        cmd.extract("RNA_I5y88", "chain x and 5y88")
        cmd.extract("cwc23_I5y88", "chain T and 5y88")
        cmd.extract("SPP382_I5y88", "chain U and 5y88")
        cmd.extract("NTR2_I5y88", "chain V and 5y88")
        cmd.extract("PRP43_I5y88", "chain W and 5y88")
        cmd.extract("SMB1_1_I5y88", "chain a and 5y88")
        cmd.extract("SMB1_2_I5y88", "chain h and 5y88")
        cmd.extract("SME1_1_I5y88", "chain b and 5y88")
        cmd.extract("SME1_2_I5y88", "chain i and 5y88")
        cmd.extract("SMX3_1_I5y88", "chain c and 5y88")
        cmd.extract("SMX3_2_I5y88", "chain j and 5y88")
        cmd.extract("SMX2_1_I5y88", "chain d and 5y88")
        cmd.extract("SMX2_2_I5y88", "chain k and 5y88")
        cmd.extract("SMD3_1_I5y88", "chain e and 5y88")
        cmd.extract("SMD3_2_I5y88", "chain l and 5y88")
        cmd.extract("SMD1_1_I5y88", "chain f and 5y88")
        cmd.extract("SMD1_2_I5y88", "chain m and 5y88")
        cmd.extract("SMD2_1_I5y88", "chain g and 5y88")
        cmd.extract("SMD2_2_I5y88", "chain n and 5y88")
        cmd.set_name("5y88", "unknown_I5y88")
        cmd.group("I5y88", "*_I5y88")
        cmd.do("order *, yes")
